# Generated by Django 4.1 on 2022-08-15 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=256)),
                ('country', models.CharField(max_length=256)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=256)),
                ('main', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
                ('temp', models.FloatField()),
                ('feels_like', models.FloatField()),
                ('temp_min', models.FloatField()),
                ('temp_max', models.FloatField()),
                ('pressure', models.FloatField()),
                ('humidity', models.FloatField()),
                ('wind_speed', models.FloatField()),
                ('city_id', models.ForeignKey(db_column='city_id', on_delete=django.db.models.deletion.PROTECT, to='weather.city')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.IntegerField()),
                ('active', models.BooleanField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='weather.city')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
