# Generated by Django 4.1 on 2022-08-18 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('weather', '0003_remove_weather_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_subscribed', to='weather.city'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscribed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='weather',
            name='city_id',
            field=models.ForeignKey(db_column='city_id', on_delete=django.db.models.deletion.PROTECT, related_name='city', to='weather.city'),
        ),
    ]
