# Generated by Django 4.1 on 2022-08-22 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_alter_subscription_city_alter_subscription_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='period',
            field=models.IntegerField(verbose_name='period, hours'),
        ),
    ]
